"""Regenerates ACL26_LALMDecoder/tables/*.tex from the manifests and results CSVs.

Every table the paper prints is generated here, so no number is transcribed by hand. In the
shape of MultilingualQASR/build_datasets_table.py: read the CSV, emit the tabular body.

Run from the repo root: python build_paper_tables.py
"""
import os

import pandas as pd

from utils import LANGUAGE_DIC, LANGUAGE_REGION, RESOURCE_TIER, TIER_ORDER, half_up

ACC = os.path.join('results_all', 'acc')
OUT = os.path.join('ACL26_LALMDecoder', 'tables')
GENERATED = '% GENERATED by build_paper_tables.py -- edit that script, not this file.\n'

# Paper-facing names. The paper calls the models LisTAya-<Variant>.
VARIANT_LABEL = {'earth': 'LisTAya-Earth', 'fire': 'LisTAya-Fire',
                 'global': 'LisTAya-Global', 'water': 'LisTAya-Water'}
REGION_LABEL = {'earth': 'Earth', 'fire': 'Fire', 'water': 'Water', None: '--'}


def fmt(v, n=2):
    return '--' if pd.isna(v) else f'{half_up(float(v), n):.{n}f}'


def write(name, body, colspec, header, caption, label, wide=False):
    """Emits a COMPLETE table environment.

    `\\input` of a bare tabular body does not work: inside an alignment TeX cannot read a file
    boundary, and the following `\\bottomrule` fails as a misplaced `\\noalign`. Generating the
    whole float sidesteps that and keeps caption and label with the numbers they describe.
    """
    os.makedirs(OUT, exist_ok=True)
    path = os.path.join(OUT, name)
    # The last row MUST keep its trailing `\\\\`: without it the row is still open when
    # `\\bottomrule` expands to `\\noalign`, which fails.
    body = body.rstrip()
    if not body.endswith(r'\\'):
        body += r' \\'
    # A 6-column table does not fit one ACL column: it silently overlaps its neighbour while
    # LaTeX reports no error. Wide tables span both columns.
    env = 'table*' if wide else 'table'
    tex = (GENERATED
           + f'\\begin{{{env}}}[t]\n\\centering\n\\setlength{{\\tabcolsep}}{{4pt}}\n'
           + f'\\begin{{tabular}}{{{colspec}}}\n\\toprule\n{header} \\\\\n\\midrule\n'
           + body + '\n\\bottomrule\n\\end{tabular}\n'
           + f'\\caption{{{caption}}}\n\\label{{{label}}}\n\\end{{{env}}}\n')
    with open(path, 'w') as f:
        f.write(tex)
    print(f'  wrote {path}')


def tab_datasets():
    """Training and evaluation configuration per language, from the training manifest."""
    m = pd.read_csv(os.path.join('data', 'manifest_training.csv'))
    ev = pd.read_csv(os.path.join('data', 'manifest_eval_sets.csv'))
    prim = ev[ev['in_domain_role'] == 'primary'].set_index('study_cell')

    rows = []
    for region in ('water', 'fire', 'earth', None):
        sub = m[m['study_cell'].map(LANGUAGE_REGION) == region] if region else \
            m[m['study_cell'].map(LANGUAGE_REGION).isna()]
        if sub.empty:
            continue
        rows.append(r'\midrule')
        for _, r in sub.sort_values('study_cell').iterrows():
            cell = r['study_cell']
            train = ' $+$ '.join(eval(r['dataset_train']))
            n = prim.loc[cell, 'num_samples'] if cell in prim.index else float('nan')
            rows.append(
                f"{LANGUAGE_DIC[cell]} & {train.replace('_', chr(92) + '_')} & "
                f"{RESOURCE_TIER.get(cell, '--').replace('_', ' ')} & "
                f"{'--' if pd.isna(n) else int(n)} \\\\")
    return '\n'.join(rows[1:])  # drop the leading \midrule


def tab_region_match():
    """Per-language matched vs mismatched, the paper's headline contrast."""
    t2 = pd.read_csv(os.path.join(ACC, 't2_region_match.csv'))
    # t2 holds one block per analysis; the paper reports the primary. Without this every
    # language appears twice.
    if 'analysis' in t2.columns:
        t2 = t2[t2['analysis'] == t2['analysis'].iloc[0]]
    t2['resource_tier'] = t2['dataset'].map(RESOURCE_TIER)
    t2['tier_rank'] = t2['resource_tier'].map({t: i for i, t in enumerate(TIER_ORDER)})
    rows = []
    for _, r in t2.sort_values(['tier_rank', 'dataset']).iterrows():
        rows.append(
            f"{LANGUAGE_DIC.get(r['dataset'], r['dataset'])} & "
            f"{REGION_LABEL.get(r.get('region'), '--')} & "
            f"{fmt(r.get('matched'))} & {fmt(r.get('mismatched_mean'))} & "
            f"{fmt(r.get('global'))} & {fmt(r.get('delta_vs_mismatched'))} \\\\")
    return '\n'.join(rows)


def tab_loss_by_tier():
    """Overfitting by resource tier: medians of per-language medians."""
    d = pd.read_csv(os.path.join(ACC, 't6_loss_by_axis.csv'))
    d = d[d['axis'] == 'resource_tier'].set_index('level')
    rows = []
    for tier in TIER_ORDER:
        if tier not in d.index:
            continue
        r = d.loc[tier]
        rows.append(f"{tier.replace('_', ' ')} & {int(r['n_languages'])} & "
                    f"{fmt(r['median_eval_loss_rise'], 3)} & "
                    f"{fmt(r['mean_frac_to_best'], 3)} \\\\")
    return '\n'.join(rows)


def tab_baselines():
    """What connector training bought, against the strongest downloadable model."""
    path = os.path.join(ACC, 't7_training_vs_baseline.csv')
    if not os.path.exists(path):
        return '% serial 11 not yet downloaded -- no contrast to print.\n'
    d = pd.read_csv(path)
    rows = []
    for _, r in d.iterrows():
        rows.append(
            f"{LANGUAGE_DIC.get(r['study_cell'], r['study_cell'])} & "
            f"{str(r['dataset']).replace('_', chr(92) + '_')} & "
            f"{'in-domain' if r['eval_domain'] == 'in_domain' else 'FLEURS'} & "
            f"{fmt(r['baseline_wer'])} & {fmt(r['trained_wer'])} & "
            f"{fmt(r['delta_wer'])} \\\\")
    return '\n'.join(rows)


def main():
    print('Generating paper tables:')
    write('tab_region_match.tex', tab_region_match(), '@{}llrrrr@{}',
          r'\textbf{Language} & \textbf{Region} & \textbf{Match} & \textbf{Mism.} & '
          r'\textbf{Global} & \textbf{$\Delta$}',
          'Best CER per language for the region-matched decoder, the mean of the two mismatched '
          'regional decoders, and LisTAya-Global. $\\Delta$ is matched minus mismatched; '
          'negative favours the matched decoder. Ordered by resource tier.',
          'tab:region-match', wide=True)
    write('tab_loss_by_tier.tex', tab_loss_by_tier(), '@{}lrrr@{}',
          r'\textbf{Tier} & \textbf{Langs} & \textbf{Eval-loss rise} & \textbf{Frac.\ to best}',
          'Overfitting by resource tier. Both columns are medians of per-language medians, so a '
          'tier with seven languages cannot outweigh one with two.',
          'tab:loss-tier')
    write('tab_baselines.tex', tab_baselines(), '@{}lllrrr@{}',
          r'\textbf{Language} & \textbf{Test set} & \textbf{Domain} & \textbf{Base.} & '
          r'\textbf{LisTAya} & \textbf{$\Delta$}',
          'WER of the best off-the-shelf baseline against the best LisTAya checkpoint on the '
          'same test set. Negative $\\Delta$ favours the trained projector.',
          'tab:baselines', wide=True)
    write('tab_datasets.tex', tab_datasets(), '@{}llrr@{}',
          r'\textbf{Language} & \textbf{WorldSpeech train} & \textbf{Tier} & \textbf{Eval $n$}',
          'Training configuration and evaluation-set size per language, generated from the run '
          'manifest.',
          'tab:dataset-generated')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
