# GENERATED by tools/preprocess/create_yamls_worldspeech_lalm.py -- do not edit.
# Regenerate after changing WORLDSPEECH_ENTRIES there.
#
# (training config stem | FLEURS eval | in-training WorldSpeech | held-out WorldSpeech)
PAIRINGS=(
    "en_us|short_ml/fleurs_en_us_test.yaml|short_ml/worldspeech_en_us_test.yaml|short_ml/worldspeech_en_au_test.yaml short_ml/worldspeech_en_jm_test.yaml short_ml/worldspeech_en_ke_test.yaml short_ml/worldspeech_en_nz_test.yaml short_ml/worldspeech_en_pk_test.yaml short_ml/worldspeech_en_sl_test.yaml short_ml/worldspeech_en_zm_test.yaml"
    "es_mx|short_ml/fleurs_es_419_test.yaml|short_ml/worldspeech_es_mx_test.yaml|short_ml/worldspeech_es_es_test.yaml short_ml/worldspeech_es_ar_test.yaml short_ml/worldspeech_es_cl_test.yaml short_ml/worldspeech_es_co_test.yaml short_ml/worldspeech_es_pe_test.yaml short_ml/worldspeech_es_pr_test.yaml short_ml/worldspeech_es_py_test.yaml short_ml/worldspeech_es_uy_test.yaml"
    "fr_ca|short_ml/fleurs_fr_fr_test.yaml|short_ml/worldspeech_fr_ca_test.yaml|short_ml/worldspeech_fr_cd_test.yaml short_ml/worldspeech_fr_ci_test.yaml"
    "ha_ng|short_ml/fleurs_ha_ng_test.yaml|short_ml/worldspeech_ha_ng_test.yaml short_ml/worldspeech_ha_td_test.yaml|"
    "sw_ke|short_ml/fleurs_sw_ke_test.yaml|short_ml/worldspeech_sw_ke_test.yaml short_ml/worldspeech_sw_tz_test.yaml|"
    "ur_pk|short_ml/fleurs_ur_pk_test.yaml|short_ml/worldspeech_ur_pk_test.yaml short_ml/worldspeech_ur_in_test.yaml|"
    "ta_in|short_ml/fleurs_ta_in_test.yaml|short_ml/worldspeech_ta_in_test.yaml|short_ml/worldspeech_ta_lk_test.yaml"
    "hi_in|short_ml/fleurs_hi_in_test.yaml|short_ml/worldspeech_hi_in_test.yaml|"
    "id_id|short_ml/fleurs_id_id_test.yaml|short_ml/worldspeech_id_id_test.yaml|"
    "mr_in|short_ml/fleurs_mr_in_test.yaml|short_ml/worldspeech_mr_in_test.yaml|"
    "am_et|short_ml/fleurs_am_et_test.yaml|short_ml/worldspeech_am_et_test.yaml|"
    "crs_sc||short_ml/worldspeech_crs_sc_test.yaml|"
)
